### ISSUE TITLE
Server Start Interface

### ISSUE THREAD

**Issue by mirjw27** [hwoodward/Remote-Card-Games#11]
**Is your feature request related to a problem? Please describe.** 

- When we play hand and foot, Helen might not always be there to do the signing in/connecting to server step - which is through command line things as far as I can tell right now. 

**Describe the solution you'd like**

- Prewritten code that can be plug-and-play used?? a button that does that??

**Describe alternatives you've considered**

**Additional context**

**Comment by hwoodward** [comment]
So plan was to use woodstar.net as the server - since it has a hostname and we could open up a port of the game communications.
Initially I was going to ssh in to start it manually and input the server side triggers that the turn order is set or the game is over  (to shut it down).
Since we want to let anyone do that we need to put a UI that can be accessed without the ssh credentials for the server. Easiest way to do that is to put it on a page under woodstar.net, such as 'woodstar.net/RemoteCards'. That UI would then need to have buttons coded to perform specific commandline operations. I don't know exactly how to do this yet - but since its a specific and hardcoded set of commands it shouldn't be too bad.
Since we don't want anyone with internet to be able to use the website to start a game we need to put some security on the endpoint before exposing the UI with the server controls. I was thinking a password like Dad has on the holiday newsletter page (he could probably even tell us how he set that up).

Summary and action items out of this:
-need to enumerate exactly what actions need to be done on the server side and keep them minimal
-need to design a website UI that allows those actions to be performed with as little room for error as possible.
-need to put that UI on woodstar.net behind some sort of security (password is current idea).

**Comment by hwoodward** [comment]
@mirjw27 
If you want this to go into a project, which it probably should, you should make a wiki page/segment about it specifying the design, where does the site live, what security does it have, what buttons/text fields are there and what do they do.

The server currently takes in the following inputs to start it: the hostname it is running on, and the port to listen for clients on. The clients then need to put in the same arguments to their staring command as well.

After starting up the server takes two inputs from a user. One is to start the game with the current players in the current order (ending the whole 'who sits where' dance). This could theoretically be replaced with a consensus mechanism later - check the wiki to see if we finalized that design and if so feel free to open an issue, and mark this as blocked until its done. The other is to declare the game over and shut the server down (otherwise it runs forever).

Both are done currently by simply hitting enter.

Once there is a specific design for the page and some consensus we can make this a feature and put it in a project.

**Comment by hwoodward** [comment]
Update:
The exact server side command is JUST to run one executable once.

**Comment by hwoodward** [comment]
oops - didn't mean to close.
