### ISSUE TITLE
UI feedback

### ISSUE THREAD

**Issue by hwoodward** [hwoodward/Remote-Card-Games#19]
**Is a part of the design not going to actually work? Please describe how and why.**
Clear and concise description of what isn't going to work or needs to be fully designed.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by slwoodward** [comment]
Attached is a mock-up of what I'm currently planning to implement first for the user display and GUI.  The program will create two windows – one showing the table, and the other the users hand.  Only the latter is used to send info to the server.  The windows are fixed size (though the size can scale with the display width and height), and will basically fill my laptop’s display.  

In this example only John has melded, and he’s in his foot, with 7 cards left.  The discard pile has 14 cards and the top one is the 3 of clubs.  The only active button in the table window is the question mark. It will explain things like
* 4: (4,1W) means that 3 natural 4s were played, and 1 wild card, and 
* active player has name in bold/underlined

The hand is shown to the right.  It has a lot of active buttons.  I’m hoping to make it so that the cards in the hand can be drawn around so that you can drag cards to the play or discard area.  No info get sent to the server until the play cards or end turn buttons are hit.  You can play cards multiple times before you end turn.  If you have no cards left you can still end turn (Zaephod).  The draw and pick-up pile won’t do anything unless it’s your turn (maybe issue a warning). Might have some change in the button’s appearance when it IS your turn….

For 11 players 3 x 4 grid works for the display. There's only a small amount of space per player, so the information has to be presented efficiently. We may want to think about how to scale things for fewer players, but I’d like to hold off on that until the game is functioning.
[displayV0_mockup.pdf](https://github.com/hwoodward/Remote-Card-Games/files/3415435/displayV0_mockup.pdf)
